# PYTHON (DAY 1)
## Introduction: Basic math in Python

In [1]:
1 # This is ruturing the number as typed. I think if it is a text it won't return

1

In [13]:
1e15 # Text throws an error but 1e6 works

1000000000000000.0

In [14]:
10 + 3

13

In [17]:
43 - 78 + (34*1)/5

-28.2

In [18]:
9 + 9/7

10.285714285714286

In [19]:
4 * 56

224

In [20]:
2 ** 7 # Raising 2 to the power of seven

128

In [21]:
pow(2,7) # This is the same as above

128

In [24]:
8 / 12 # Dividing a number by another

0.6666666666666666

In [30]:
8 / 8.17e2 # Dividing an integer by an exponentiated number

0.009791921664626682

In [31]:
8.17e2 # Just what does this print?

817.0

In [23]:
5 // 2

2

In [9]:
4 % 7

4

In [10]:
8 / 9

0.8888888888888888

In [11]:
(9 + 9) / (56 * 6)

0.05357142857142857

In [12]:
name = 1

In [13]:
name

1

In [14]:
print(name)

1


In [15]:
dhruv = 10

In [16]:
dhruv

10

In [17]:
print(dhruv)

10


In [18]:
x = 9
y = 5

In [19]:
z = x + y

In [20]:
z

14

In [21]:
print(z)

14


In [22]:
s = x - y

In [23]:
s

4

In [24]:
_+ y # Underscore is the previous value

9

## Combining strings together

In [25]:
 subject = 'python'

In [26]:
subject

'python'

In [27]:
name = 'language'

In [28]:
name

'language'

In [29]:
learn = subject + name

In [30]:
learn

'pythonlanguage'

In [31]:
name +' learning'

'language learning'

## Indexing strings

In [32]:
name = 'language'

In [33]:
name[0] # This is the first index

'l'

In [34]:
#name[8] # 8 is beyond the lenght of the name

In [35]:
name[-5] # This is reverse direction

'g'

## Printing more strings together

In [36]:
var1 = ' computer science'

In [37]:
var2 = ' information practices'

In [38]:
var1

' computer science'

In [39]:
var2

' information practices'

In [40]:
print(var1, ' and ', var2)

 computer science  and   information practices


## Literals in Python
### String literals

In [41]:
# literals in python can be defined as number, text or other data that represent values to be stored in variables

In [42]:
# examlple of string literals in python
name = 'python'

In [43]:
name

'python'

### Integer literals

In [44]:
age = 22

In [45]:
age

22

In [46]:
# float literals (numeric literal)
height = 6.2

In [47]:
height

6.2

## Operators in Python

Operators can be defined as symbols that are used to perform operations on operands 

Types of operators
1. ARITHMETIC OPERATORS
2. RELATIONAL OPERATORS
3. ASSIGNMENT OPERATORS
4. LOGICAL OPERATORS
5. IDENTITY OPERATORS
6. MEMBERSHIP OPERATORS

### Arithmetic operators- (AO)
AO are used to perform arithmetic operations like addition, multiplications etc

#### ' + ' 
Performs addition of two numbers a + b

In [48]:
a = 4
b = 3
a + b

7

####  ' - ' 
Subtraction operators perform subtraction of numbers a - b

In [49]:
a - b

1

#### ' / ' 

Performs division of two numbers a / b


In [50]:
a / b

1.3333333333333333

#### ' * ' 
Performs multiplication of two numbers a * b


In [51]:
a * b

12

#### ' % ' 
MODULUS = returns the remainder in division of two numbers a % b


In [52]:
a % b

1

#### ' // ' 
Floor division = removes digits after decimal point a // b


In [53]:
a // b

1

#### ' ** ' 
Exponent = Performs raise to power 


In [54]:
a ** b

64

### Relational Operators (RO)


RO are used to compare two values 

#### '==' 
Equal to, return true if a equal to b a == b


In [55]:
a = 5
b = 4
a == b

False

#### '!=' 
Not equal, return true if a is not equal to b a != b


In [56]:
a != b

True

#### '>' 
Greater than, return true if a is greater than b  a > b


In [57]:
a > b

True

#### '>=' 
Greater than or equalto, returns true if a is greater than b or a is equal to b  a >= b


In [58]:
a >= b


True

In [59]:
# '<'
# '<='

### Assignment Operators (AO)
Used to assign values to variables


#### ' = ' 
Assign the values from right side operands to left side operands a = b


In [60]:
a = 5
b = 4
a = b

In [61]:
a

4

In [62]:
b

4

#### ' += ' 
Adds 2 numbers and assigns the result to left operands a += b


In [63]:
a = 5
b = 4
a += b

In [64]:
a

9

In [65]:
b

4

#### ' /= ' 
Divides 2 numbers and assigns the result to left operand a /= b


In [66]:
a = 5
b = 4
a /= b

In [67]:
a

1.25

In [68]:
b

4

#### ' -= ' 
Subtracts two numbers and assigns the result to left operands a -= b


In [69]:
a = 5
b = 4
a -= b

In [70]:
a

1

In [71]:
b

4

#### ' *= ' 
Multiplys two numbers and assign the result a *= b


In [72]:
a = 5
b = 4
a *= b

In [73]:
a

20

In [74]:
b

4

#### ' %= ' 
Modulus two numbers and assign the result to left operands a %= b

In [75]:
a = 5
b = 4
a %= b

In [76]:
a

1

In [77]:
b

4

#### ' //= ' 
Performs floor division on two numbers and assign the result to left operands a //= b 


In [78]:
a = 5
b = 4
a //= b

In [79]:
a

1

In [80]:
b

4

#### ' **= ' 
Calculates power on operators and assigns the result to left operands a **= b


In [81]:
a = 5
b = 4
a **= b

In [82]:
a

625

In [83]:
b

4

### Logical Operators (LO)
Logical operators are used to perform logical operations on the given 2 variables 


1. 'and' returns true if both conditions are trueeg x and y
2. 'or' return true if either or both condition are true x or y
3. 'not' reverse the condition not(a>b)

In [84]:
a = 30
b = 20
if(a == 30 and b == 20):
    print('hello')

hello


### Membership Operators (MO)
MO in python are used to validate whether a value is found within a sequence such as strings, lists or tuples

1. 'in' returns true if value exists in the sequence, else false a in list
2. 'not in' return true if value doesn't exist in the sequence, else false a not in list


In [85]:
a = 22
listi = [22, 99, 27, 31]
in_ans = a in listi
notin_ans = a not in listi
print(in_ans)
print(notin_ans)

True
False


### Identity Operators (IO)

IO in python compare the memory location of two objects
1.'is' return true if two variables point the same object, else false  ' a is b'
2. 'is not' return true if 2 variables point the different objects, else false
 'a is not b'

In [86]:
# eg
a = 34
b = 34

if(a is b):
    print(' both a and b has same identity ')
else:
    print('a and b has different identity')

b = 99 # Changing the value of variable b

if (a is b):
    print(' both a and b has same identity ')
else:
    print('a and b has different identity')

 both a and b has same identity 
a and b has different identity


## Variables in Python

Variable is a name given to a memory location. A variable can consider as container which holds values. python is a 
type infer language that means you don't need to specify the datatype of variables.

### Assigning values to variable

In [87]:
name = 'python' # String data type
sume = None # A variable without value
a = 23 # Integer 
b = 2.6 # Float
sum = a + b
print(sum)

25.6


### Multiple assignment 
Assign a single value to many variables

In [88]:
a = b = c = 1 # single value to multiple variables
a = b = 1,2 # multiple values to multiple variables
a,b = b,a # value of a is swaped 

## Input and Output
### print() 
Function in python is used to print output on the screen.
Syntax of print function 

In [89]:
print(122)

122


In [90]:
print('hello india')

hello india


In [91]:
print('computer', 'science')

computer science


In [92]:
print('computer', 'science', sep = ' & ')

computer & science


In [93]:
print('computer', 'science', sep = ' & ', end='.')

computer & science.

## Introduction to Data Types in Python

Most of the computer programming languages a support data types 
Data type specifies which type of value a variable can store. dtype() function

Data types in python:
1. numbers
2. string
3. boolean
4. list
5. tuple
6. set
7. dictionaru

### Numbers in Python
It is used to store numeric values

Types of numeric values:

1. integers
2. floating/continuous
3. complex numbers

#### Integers
Integers or int are positive or negative numbers with no decimals

In [94]:
a = 100
b = -200
c = 1 * 5
print(a)
print(b)
print(c)

100
-200
5


- Type conversion of integers. int() function converts any data types to integers


In [95]:
a = "101" # string
b = int(a) # converts string data type to integers
c = int(22.4) # converts float data type to integer
print(a)
print(b)
print(c)

101
101
22


#### Floating point numbers
It is a positive and negative real numbers with decimal points

In [96]:
a = -101.2
b = -102.5
c = 11.23
type(c)

float

- Type conversion of floating point numbers. float() function converts any data type to floating point numbers

In [97]:
a = '301.4' # string
b = float(a) # converts string data type to float
c = float(122) # converts integer data type to floating point number
print(b)
print(c)

301.4
122.0


#### Complex numbers 
Complex numbers are combination of a real and imaginary part. 
Complex numbers are in the form of X +Yj, where X is a real part and Y is an imaginary part

In [98]:
a = complex(5)
print(a)

(5+0j)


In [99]:
b = complex(101,23)

In [100]:
print(b)

(101+23j)


### Strings in Python
A string is a sequence of a characters. In python we can create string using single (' ') or double(" ")
#### Creating a string


In [101]:
str = 'computer science'
print('str-', str) # print string

str- computer science


#### Indexing a string

In [102]:
print('str[0]-', str[0]) # print first character 'c'

str[0]- c


In [103]:
print('str[1:3]-', str[1:3]) # print string starting from 1 to 3

str[1:3]- om


In [104]:
print('str[3:1]-', str[3:]) # print string from 3rd

str[3:1]- puter science


#### Arithmetic with strings and positive integers

In [105]:
print('str*2-', str*2) # print string two times

str*2- computer sciencecomputer science


### Boolean in Python
Used to store two possible values either true or false

In [106]:
str = 'comp sc'
bool = str.isupper()
bal = str.islower()
print(bool)
print(bal)

False
True


### Lists in python
Lists are collections of items and each item has its own index value

In [107]:
listi = [6, 8]
print(listi)
listi[0] = 55
print(listi)

[6, 8]
[55, 8]


In [108]:
listi = [[5, 6],[8, 10]]
listi[1]

[8, 10]

# PYTHON (DAY 2)

In [109]:
2+5

7

In [110]:
def myfun(fname):
    print(fname)
myfun("Onyango")

Onyango


In [111]:
def my_function(fname, lname):
    print(fname + " " + lname)
my_function("Wyclife", "Agumba")

Wyclife Agumba


In [112]:
def my_function(x):
    return 5 * x
print(my_function(3))
print(my_function(5))
print(my_function(9))

15
25
45


In [113]:
import calendar
cal = calendar.month(2022, 1)
print("Here is the calendar:")
print(cal)
import math
print(math.pi)
print(math.pow)

Here is the calendar:
    January 2022
Mo Tu We Th Fr Sa Su
                1  2
 3  4  5  6  7  8  9
10 11 12 13 14 15 16
17 18 19 20 21 22 23
24 25 26 27 28 29 30
31

3.141592653589793
<built-in function pow>


In [114]:
import math

In [115]:
print(math.pi)

3.141592653589793


In [116]:
print(math.pow(2,5))

32.0


In [117]:
print(math.factorial(6))

720


In [118]:
li = "how are you"

In [119]:
print(li.find("are"))

4


# PYTHON (DAY 3): Numpy

## What is numpy

In [120]:
# High level mathematical computations...many maths functions
# multidimensional arrays and matrices
# works with n-dimensional arrays
# basic linear algebra functions
# basic fourier transforms
# sophisticated random number capabilities
# Integrating so many platforms like C++ Fortran etc

In [121]:
import random as r
import numpy as np
a = np.array([1, 2, 3]) # One dimensional array
print(a)

[1 2 3]


In [122]:
b = np.array(r.sample(range(10, 100), 20), ndmin = 1)
print(b)

[46 18 57 58 68 50 67 98 66 20 30 80 47 78 56 54 86 79 32 37]


In [123]:
b = np.array(r.sample(range(10, 100), 20), ndmin = 2)
print(b)

[[67 28 89 56 15 46 96 62 57 52 14 65 44 39 82 59 51 64 93 94]]


In [124]:
b = np.array(r.sample(range(10, 100), 20), ndmin = 3)
print(b)

[[[57 11 49 88 14 68 84 71 20 87 52 72 48 80 65 46 75 81 63 70]]]


In [125]:
a = np.array([[[1, 2, 3], [4,5,6], [7,8,9], [10, 11, 12]]])
print(a)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


In [126]:
a = np.array([1, 2, 3, 4, 5, 6,7])
print(a[5])

6


In [127]:
print(a[2:4])

[3 4]


In [128]:
a = np.array([[1, 2, 3], [4,5,7]])
print(a[1][2])

7


In [129]:
x = np.zeros(10, dtype = int)
print(x)

[0 0 0 0 0 0 0 0 0 0]


In [130]:
x = np.zeros(10, dtype = float)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [131]:
x = np.zeros((2,2), dtype = float)
print("\nZero Array of 5,5 char -->\n", x)


Zero Array of 5,5 char -->
 [[0. 0.]
 [0. 0.]]


In [132]:
x = np.ones(5)
print("Ones Array -->\n", x)

Ones Array -->
 [1. 1. 1. 1. 1.]


In [133]:
x = np.ones((5,5), dtype=int)
print("Ones Array -->\n", x)

Ones Array -->
 [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## Array for numerical ranges

In [134]:
x = np.arange(10, 20, 2)
print("\nArray  -->\n", x)


Array  -->
 [10 12 14 16 18]


In [135]:
x = np.arange(10, 20)
print("\nArray  -->\n", x)


Array  -->
 [10 11 12 13 14 15 16 17 18 19]


In [136]:
x = np.arange(10, 20, 2)
print("\nArray  -->\n", x)


Array  -->
 [10 12 14 16 18]


In [137]:
x = np.arange(10, 20, 3)
print("\nArray  -->\n", x)


Array  -->
 [10 13 16 19]


In [138]:
x = np.arange(10, 20, 4)
print("\nArray  -->\n", x)


Array  -->
 [10 14 18]


In [139]:
x = np.arange(10, 22, 4)
print("\nArray  -->\n", x)


Array  -->
 [10 14 18]


## Slicing: Sclice

In [140]:
a = np.arange(15)
s = slice(2, 7, 2)
print("\n Slice \n", s)
print(a[s])


 Slice 
 slice(2, 7, 2)
[2 4 6]


In [141]:
a = np.arange(15)
s = slice(2, 10, 2)
print("\n Slice \n", s)
print(a[s])


 Slice 
 slice(2, 10, 2)
[2 4 6 8]


In [142]:
a = np.arange(15)
s = slice(5, 10, 3)
print("\n Slice \n", s)
print(a[s])


 Slice 
 slice(5, 10, 3)
[5 8]


In [143]:
a = np.arange(15)
s = slice(5, 10, 3)
print("\n Slice \n", s)
print(a[s])


 Slice 
 slice(5, 10, 3)
[5 8]


## Indexing

In [144]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a[...,1])
print(a[1,...])
print(a[...,1:])

[2 4 5]
[3 4 5]
[[2 3]
 [4 5]
 [5 6]]


In [145]:
a = np.array([[1,2,3.,7],[3,4,5,7],[4,5,6,7]])
print(a[...,1])
print(a[1,...])
print(a[...,2:])

[2. 4. 5.]
[3. 4. 5. 7.]
[[3. 7.]
 [5. 7.]
 [6. 7.]]


In [146]:
print(a[2:,...])

[[4. 5. 6. 7.]]


In [147]:
print(a[1:,...])

[[3. 4. 5. 7.]
 [4. 5. 6. 7.]]


## Multiplication

In [150]:
import tensor as gpd

ModuleNotFoundError: No module named 'pytorch'

In [ ]:
a = np.array([1,2,3,4])
b = np.array([10, 11, 12, 13])
c = a * b
print(c)

In [ ]:
a = np.arange(0,60,5)
a = a.reshape(3,4)
print('Original array is:')
print(a)

In [ ]:
print('\nModified array is:')
for x in np.nditer(a):
    print(x)


In [ ]:
a = np.arange(0,60,5)
a = a.reshape(2,3,2)
print('Original array is:')
print(a)

In [ ]:
print('\nModified array is:')
for x in np.nditer(a):
    print(x)

## Statistical functions

In [ ]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(np.median(a))

In [ ]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(np.median(a, axis=0))

In [ ]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(np.median(a, axis=1))

In [ ]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(np.mean(a, axis=0))

In [ ]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(np.mean(a, axis=1))

In [ ]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(np.average(a, axis=0))

In [ ]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(np.std(a, axis=0))

## np.where

In [ ]:
x = np.arange(9.).reshape(3,3)
print(x)

In [ ]:
y = np.where(x > 3)
print(y)

In [ ]:
print(x[y])

In [ ]:
x = np.arange(9.).reshape(3,3)
print(x)
condition = np.mod(x,2) == 0
print(condition)
print(np.extract(condition, x))

# PYTHON (DAY 4):-

In [ ]:
# PANDAS open source library for data analysis 


In [ ]:
# The series - declaring series
# selecting the internal elements
# assigning vslues to elements
# defining a series
# filtering values
# operations
# evaluating values
# NaN values

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# Series minus one
s = pd.Series([7, 'Heisenberg', 3.14, -1789710578, 'Happy Eating!'])

In [ ]:
a = pd.Series(np.random.randn(5), index = ["a", "b", "c", "d", "e"])
a

In [ ]:
s = pd.Series([7, 'Heisenberg', 3.14, -1789710578, 'Happy Eating!'], index = ['A', 'Y', 'C', 'Z', 'E'])
s

In [ ]:
s.index

In [ ]:
a.index

In [ ]:
d = {"b": 1, "a":0, "c": 2}
pd.Series(d)

In [ ]:
d = {"b": 1.0, "a": 8.80, "c": 2.45}
pd.Series(d)


In [ ]:
pd.Series(d)
d['b']

In [ ]:
# Indexing with boolean values

In [ ]:
# Dataframes

In [ ]:
b = np.array([1, 2, 3, 4, 5])
b[4]

In [ ]:
arr = np.arange(10)
arr

In [ ]:
arr[5]

In [ ]:
arr[5:8] # Does not include the eight element

In [ ]:
arr[:4] # First four elements

In [ ]:
arr[5:] # From fifth to the last element

In [ ]:
arr[7:9] = 10
arr

In [ ]:
arr2d =  np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2d

In [ ]:
arr2d =  np.array([[10,23], [26,89]])

arr2d[1]

In [ ]:
arr2d =  np.array([[10,23], [26,89]])

arr2d[0,1]

In [ ]:
arr2d =  np.array([[10,23], [26,89]])

arr2d[1,0]

In [ ]:
arr2d =  np.array([[10,23], [26,89]])

arr2d[1,1]

In [ ]:
arr[1:6]

In [ ]:
arr2d[1, :2]

In [ ]:
# Boolean
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
names

In [ ]:
data = np.random.randn(7, 4)
data

In [ ]:
arr = np.arange(16).reshape(2,2,4)
arr

In [ ]:
arr.transpose((1,0,2))
arr

In [ ]:
data = 25
s = np.sqrt(data)
s
p = np.exp(s)
p

In [ ]:
np.tan(data)

In [ ]:
np.tan(30)

In [ ]:
# Selecting the internal elements of a data frame

In [ ]:
# Reading data

In [ ]:
data = pd.read_csv('/home/wycology/Downloads/pandasss.csv')
data.head()

# PYTHON (DAY 5):-

In [ ]:
import numpy as np
import pandas as pd

## Creating 
### Pandas series from list

In [ ]:
my_data = [10, 20, 30, 40, 50]
labels = ["a", "b", "c", "d", "e"]

In [ ]:
pd.Series(data = my_data) # default index starts at 0

In [ ]:
pd.Series(data = my_data, index = labels) # passing index values to the series

In [ ]:
pd.Series(my_data, labels)

In [ ]:
b = pd.Series(my_data, labels)
b

### Pandas series from numpy array

In [ ]:
arr = np.array(my_data)
arr

In [ ]:
pd.Series(data = arr)

In [ ]:
pd.Series(data = arr, index = labels)

### Pandas series using dictionary

In [ ]:
d = {'a': 100, 'b': 200, 'c': 300, 'd': 400}

In [ ]:
d

In [ ]:
pd.Series(d)

In [ ]:
pd.Series(data = [sum, len])

### Grab information from pandas series

In [ ]:
ser1 = pd.Series(data = [1,2,3,4], index = ['Red', 'Green', 'Blue', 'Orange'])

In [ ]:
ser1

In [ ]:
ser2 = pd.Series(data = [1,2,5,4], index = ['Red', 'Green', 'Yellow', 'Orange'])

In [ ]:
ser2

In [ ]:
ser2['Green']

In [ ]:
ser1['Blue']

In [ ]:
ser3 = pd.Series(data = ['a', 'b', 'c', 'd', 'e'])

In [ ]:
ser3

In [ ]:
ser3[0]

In [ ]:
ser1[0:4]

In [ ]:
ser1

In [ ]:
ser2

In [ ]:
ser1 + ser2

## Dataframes Part 1

In [ ]:
import numpy as np
import pandas as pd
from numpy.random import randn
np.random.seed(101)

### Creating a dataframe

In [ ]:
df = pd.DataFrame(data = randn(5,4), index = ["a", "b", "c", "d", "e"], columns = ["w", "x", "y", "z"])

In [ ]:
df

### Indexing and selection

In [ ]:
df['w'] # Picking the w column

In [ ]:
df[['x', 'z']] # Picking x and z columns

In [ ]:
type(df['w']) # This is of type Series

In [ ]:
type(df) # This is of type DataFrame

In [ ]:
type(df[['x', 'z']]) # This is of type DataFrame again

In [ ]:
df[['x', 'z']] # Make use of two square brackets

### Adding a new column in a DataFrame

In [ ]:
df['new'] = df['w'] + df['x']

In [ ]:
df

In [ ]:
df.drop(labels = 'new', axis = 1)

In [ ]:
df['new'] = df['w'] // df['x']

In [ ]:
df

### Removing a column from a DataFrame

In [ ]:
df.drop(labels = 'new', axis = 1)

In [ ]:
df # The new column is still present in the DataFrame

In [ ]:
df.drop(labels = 'new', axis = 1, inplace = True) # Using inplace = True, removes it completely

In [ ]:
df # the new column is removed completely

### Removing a row from a DataFrame

In [ ]:
df.drop('b', axis = 0) # 0 means we are refering to rows, so row b is dropped
# Adding inplace = True would remove row c completely just like columns

### Selecting some rows in a DataFrame

In [ ]:
df.loc['c']

In [ ]:
df.loc['e']

In [ ]:
type(df.loc['e'])

### Selecting the subset of rows and columns

In [ ]:
df

In [ ]:
df.loc['e', 'x'] # Particular cell

In [ ]:
df.loc['c', 'x']

In [ ]:
df.loc[['d', 'e'], ['y', 'z']]

In [ ]:
df.loc[['a', 'e'], ['x', 'z']]

In [ ]:
df.loc[['a', 'e', 'b'], ['x', 'z', 'w']]

## DataFrames Part 2

In [ ]:
import numpy as np
import pandas as pd
from numpy.random import randn
np.random.seed(101)

In [ ]:
df = pd.DataFrame(data = randn(5,4), index = ["a", "b", "c", "d", "e"], columns = ["w", "x", "y", "z"])

In [ ]:
df

### Conditional Selection

In [ ]:
df > 0

In [ ]:
b = df > 0

In [ ]:
b

In [ ]:
df[b]

In [ ]:
df[df > 0]

In [ ]:
df['w'] > 0

In [ ]:
d = df['w'] > 0

In [ ]:
d

In [ ]:
df[d] # c row is dropped because it had a False

In [ ]:
df[df['w'] > 0]

In [ ]:
df

In [ ]:
df[(df['w'] > 0) & (df['y'] > 1)] # and logical operator

In [ ]:
df[(df['w'] > 0) | (df['y'] > 1)] # or logical operator

### Indexing DataFrame

In [ ]:
df

In [ ]:
df.reset_index()

In [ ]:
new_index = ['R', 'G', 'B', 'O', 'Y']

In [ ]:
new_index

In [ ]:
df['Colors'] = new_index

In [ ]:
df

In [ ]:
df.set_index('Colors') # Am wondering why the column names w to z jumped up

## DataFrames Part 3

In [ ]:
import numpy as np
import pandas as pd
from numpy.random import randn
np.random.seed(102)

In [ ]:
outside = ['Red','Red','Red','Green','Green','Green']
inside = [1,2,3,1,2,3]

In [ ]:
hier_index = list(zip(outside,inside))

In [ ]:
hier_index

In [ ]:
multi_index = pd.MultiIndex.from_tuples(hier_index, names = ['Colors', 'Numbers'])

In [ ]:
multi_index

In [ ]:
df = pd.DataFrame(data = randn(6,2), index=multi_index, columns = ['A', 'B'])

In [ ]:
df

In [ ]:
df.loc['Red'].loc[1]['A']

In [ ]:
df.loc['Green'].loc[2]['B']

In [ ]:
df.index.names

In [ ]:
df.index.names = ['Col', 'Num']

### Cross section

In [ ]:
df

In [ ]:
df.loc['Red']

In [ ]:
df.loc['Green']

In [ ]:
df.xs('Red')

In [ ]:
df.xs(1, level = 'Num')

## Missing data

In [ ]:
import numpy as np
import pandas as pd

### CReate DataFrame with missing values

In [ ]:
d = {"A": [1,2,np.nan], "B":[3, np.nan, np.nan], "C":[4,5,6]}

In [ ]:
df = pd.DataFrame(d)

In [ ]:
df

### dropna

In [ ]:
df.dropna() # Drops nas along rows by default

In [ ]:
df.dropna(axis = 1) # Dropa nas column-wise

In [ ]:
df.dropna(axis = 0) # Also works with rows

In [ ]:
df.dropna(thresh = 2, axis = 0) # Only leave rows with less than two NaNs

In [ ]:
df.dropna(thresh = 1, axis = 1)

### fillna

In [ ]:
df.fillna(value = 'New Value')

In [ ]:
df['A'].fillna(value = df['A'].mean()) # can also take min, max, average, sum

## Groupby method

In [ ]:
team_data = {'Company': ['Apple', 'Apple', 'FB', 'FB', 'Google', 'Google'], 
             'Person': ['Mark', 'Tom', 'John', 'Sara', 'Mia', 'Emma'], 
             'Sales': [200, 150, 350, 125, 260, 180]}

In [ ]:
team_data

In [ ]:
df = pd.DataFrame(team_data)

In [ ]:
df

In [ ]:
df.groupby(by = 'Company')

In [ ]:
b = df.groupby('Company')

In [ ]:
b.mean()

In [ ]:
b.sum()

In [ ]:
b.sum().loc['Apple']

In [ ]:
df.groupby(by = 'Company').sum().loc['FB']

In [ ]:
b.count()

In [ ]:
b.max()

In [ ]:
b.min()

In [ ]:
df.groupby(by = 'Company').describe()

In [ ]:
df.groupby(by = 'Company').describe().transpose()

In [ ]:
df.groupby(by = 'Company').describe().loc['FB']

## Merging, Joining and Concatenating

In [ ]:
import pandas as pd

### DataFrames Concatenations

In [ ]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                   'B': ['B0', 'B1', 'B2', 'B3'],
                   'C': ['C0', 'C1', 'C2', 'C3'],
                   'D': ['D0', 'D1', 'D2', 'D3']},
                  index = [0, 1, 2, 3])

df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                   'B': ['B4', 'B5', 'B6', 'B7'],
                   'C': ['C4', 'C5', 'C6', 'C7'],
                   'D': ['D4', 'D5', 'D6', 'D7']},
                  index = [4, 5, 6, 7])

df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                   'B': ['B8', 'B9', 'B10', 'B11'],
                   'C': ['C8', 'C9', 'C10', 'C11'],
                   'D': ['D8', 'D9', 'D10', 'D11']},
                  index = [8, 9, 10, 11])

In [ ]:
df1

In [ ]:
df2 

In [ ]:
df3

In [ ]:
pd.concat(objs = [df1, df2, df3])

In [ ]:
pd.concat(objs = [df1, df2, df3], axis = 1)

### DataFrames Merging

In [ ]:
df4 = pd.DataFrame({'Key': ['K0', 'K1', 'K2', 'K3'],
                   'A': ['A0', 'A1', 'A2', 'A3'],
                   'B': ['B0', 'B1', 'B2', 'B3']})

df5 = pd.DataFrame({'Key': ['K0', 'K1', 'K2', 'K3'],
                   'C': ['C0', 'C1', 'C2', 'C3'],
                   'D': ['D0', 'D1', 'D2', 'D3']})

In [ ]:
df4

In [ ]:
df5

In [ ]:
pd.merge(left = df4, right = df5, on = 'Key')

In [ ]:
df6 = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                    'key2': ['K0', 'K1', 'K0', 'K1'],
                   'A': ['A0', 'A1', 'A2', 'A3'],
                   'B': ['B0', 'B1', 'B2', 'B3']})

df7 = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                    'key2': ['K0', 'K0', 'K0', 'K0'],
                   'C': ['C0', 'C1', 'C2', 'C3'],
                   'D': ['D0', 'D1', 'D2', 'D3']})

In [ ]:
df6

In [ ]:
df7

In [ ]:
pd.merge(left = df6, right = df7, on = ['key1', 'key2'])

## DataFrames Join

In [ ]:
df8 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                   'B': ['B0', 'B1', 'B2', 'B3']},
                  index = ['K0', 'K1', 'K2', 'K3'])

df9 = pd.DataFrame({'C': ['C0', 'C1', 'C2', 'C3'],
                   'D': ['D0', 'D1', 'D2', 'D3']},
                  index = ['K0', 'K1', 'K2', 'K3'])

In [ ]:
df8

In [ ]:
df9

In [ ]:
df8.join(df9)

## Reading and writing files in pandas

In [ ]:
import pandas as pd

In [ ]:
pwd

In [ ]:
pd.read_csv('names.csv') # GIve the name of the csv file

In [ ]:
b = pd.read_csv('names.csv')

In [ ]:
b

In [ ]:
df.to_csv('savedone.csv')

# PYTHON (DAY 6):- Dr. Pooja

## Data visualization with Matplotlib

In [ ]:
# Matplotlib is a module for plotting data or visualizing data

In [ ]:
# It supports a lot of backend

In [ ]:
# It has great strenght in data display. There are also:
# seaborn
# ggplot
# bokhen

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data:- pandas pd.read_csv('')
pandas : - dataframes

plt.plot() - line chart

plot.xlabel
plot.xlabel
plot.ylabel
plt.xticks
plt.yticks

plt.legend()
plt.title()
plt.show()

In [ ]:
data = pd.read_csv('titanic.csv')
data.head()

In [ ]:
plt.plot(data.Freq)

In [ ]:
plt.plot(data.Freq)
plt.xlabel('person')
plt.ylabel('age')

In [ ]:
plt.plot(data.Freq)
plt.xlabel('person')
plt.ylabel('age')
plt.legend('Frequency')

In [ ]:
plt.hist(data.Freq)

In [ ]:
plt.hist(data['Freq'], facecolor = 'purple', bins = 10)

In [ ]:
x = [x for x in range(100)]
plt.hist(x)

In [ ]:
pop = []
for i in range(50):
               n = np.random.randint(190, 230)
               n = n/100
               pop.append(n)

In [ ]:
plt.hist(pop)

In [ ]:
plt.hist(pop, bins = 5)

In [ ]:
plt.hist(pop, bins = 10)

In [ ]:
plt.hist(pop, color = 'purple')

In [ ]:
plt.hist(pop, color = 'purple', orientation = 'horizontal')

In [ ]:
plt.hist(pop, color = 'purple', orientation = 'horizontal')
plt.xscale('log')

In [ ]:
plt.hist(pop, color = 'purple')
plt.xticks([0, 20, 30, 50])

In [ ]:
plt.hist(pop, bins = 5, facecolor = 'purple', edgecolor = 'yellow')


In [ ]:
plt.hist(pop, bins = 5, facecolor = 'magenta', edgecolor = 'cyan', cumulative = True)

In [ ]:
plt.hist(pop, bins = 10, facecolor = 'purple', edgecolor = 'yellow', range = (1.5, 2.0))

In [ ]:
# 

In [ ]:
x = np.random.rand(5)
y = np.random.rand(5)
s1 = [10, 20, 30, 40, 100]
c1 = np.random.rand(5)

In [ ]:
plt.scatter(x, y)

In [ ]:
plt.scatter(x, y, s = s1) # Size of the dots changed

In [ ]:
plt.scatter(x, y, s = s1, c = c1) # colors assigned

In [ ]:
plt.scatter(x, y, s = s1) # Size of the dots changed

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

pop = []
for i in range(50):
               n = np.random.randint(190, 230)
               n = n/100
               pop.append(n)

In [ ]:
gdp_cap= []
for i in range(50):
               n = np.random.randint(155, 389)
               n = n/100
               gdp_cap.append(n)

In [ ]:
life_exp = []
for i in range(50):
               n = np.random.randint(10, 120)
               n = n/100
               life_exp.append(n)

In [ ]:
plt.scatter(gdp_cap, pop, s = life_exp)

In [ ]:
# Pie Chart

In [ ]:
labels = 'Python', 'C++', 'Ruby', 'Java'
sizes = [310, 30, 145, 110]

In [ ]:
plt.pie(sizes)

In [ ]:
plt.pie(sizes, labels = labels)

In [ ]:
plt.pie(sizes, labels = labels, colors=['magenta', 'cyan', 'blue', 'green', 'lightblue'])

In [ ]:
c=['magenta', 'cyan', 'blue', 'green', 'lightblue']
e = (0, 0.2, 0, 0)
plt.pie(sizes, labels = labels, colors=c, explode = e, shadow=True)

In [ ]:
# Bar graphs

In [ ]:
x = np.arange(4)
money = [1.5e5, 2.5e6, 5.5e6, 2.0e7]

In [ ]:
plt.bar(x, money)

In [ ]:
plt.bar(x, money, color = 'purple')

In [ ]:
plt.bar(x, money, color = 'purple')
plt.xticks(x, ('Bill', 'Fred', 'Mary', 'Sue'))

In [ ]:
df2 = pd.DataFrame(np.random.rand(10, 4), columns = ['a', 'b', 'c', 'd'])
df2.plot.bar()

In [ ]:
df2 = pd.DataFrame(np.random.rand(10, 4), columns = ['a', 'b', 'c', 'd'])
df2.plot.bar(stacked = True)

In [ ]:
# Area plot ... NaNs are automatically filled by 0 zero...can handle with dropna and fillna

In [ ]:
df = pd.DataFrame(np.random.rand(10, 4), columns = ['a', 'b', 'c', 'd'])
df.plot.area()

In [ ]:
# Boxplot min, 1st quart, median, 3rd and max...also IQR 1.35 of standard deviation

In [ ]:
df = pd.DataFrame(np.random.rand(10, 4), columns = ['a', 'b', 'c', 'd'])
df.boxplot()

In [ ]:
df = pd.DataFrame(np.random.rand(10, 4), columns = ['a', 'b', 'c', 'd'])
color = dict(boxes = 'Purple', whiskers = 'DarkOrange', )
df.plot.box()

# PYTHON (DAY 7):- Dhruv Govil +919540855058

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sn

In [ ]:
mt = pd.read_csv('mtcars.csv') 

In [ ]:
mt

## Drop some columns

In [ ]:
m1 = mt.drop(['mpg', 'disp', 'wt', 'am'], axis = 1)
m1

In [ ]:
mt.shape

In [ ]:
m1.shape

In [ ]:
m2  = mt.drop(columns = ['hp', 'vs', 'carb', 'gear'])
m2

## Drop rows

In [ ]:
mt.shape

In [ ]:
m2.shape

In [ ]:
# Drop rows

In [ ]:
m3 = mt.drop([0, 12, 6, 27, 31]) # State the row indices to be dropped
m3

## Statistics

In [ ]:
mt

In [ ]:
mt.dtypes

## Data summaries

In [ ]:
mt.describe()

In [ ]:
mt['mpg'].median()

In [ ]:
mt['mpg'].mean()

In [ ]:
mt.head()

In [ ]:
mt.head(10)

In [ ]:
mt.tail() # last five observations

In [ ]:
mt.tail(10)

In [ ]:
air = pd.read_csv('airquality.csv')
air

In [ ]:
air.describe()

In [ ]:
air.count() # number of missing values

## Find out the total number of missing values

In [ ]:
air.isnull().sum()

In [ ]:
air['Ozone'].isnull().sum() # Can check for only one variable

In [ ]:
air[['Ozone', 'Solar.R']].isnull().sum() # Can check for more than one variable 

In [ ]:
# how to check the frequency of particular columns
mt['cyl'].value_counts()

In [ ]:
mt['mpg'].value_counts()

## Visualization

In [ ]:
import matplotlib.pyplot as plt

### Scatter plot

In [ ]:
mt.plot.scatter('mpg', 'wt')

In [ ]:
mt.plot.scatter('mpg', 'wt', 'hp') # The third variable will be used for bubble size

In [ ]:
mt.corr()

In [ ]:
mt.mean() # Gives the mean of each column

In [ ]:
mt.mean(axis = 1) # This is mean row-wise

In [ ]:
mt.head(1)

In [ ]:
(21 + 6 + 160 + 110 + 3.9 + 2.62 + 16.46 + 1 + 4 + 4) / 11

In [ ]:
mt[['mpg', 'cyl']].head(1).mean(axis = 1) # Mean of first two columns in first row

In [ ]:
(21 + 6) / 2

In [ ]:
import seaborn as sns

In [ ]:
# sns.pairplot(mt)

In [ ]:
# the iloc indexer for pandas dataframe is used for selection by position
mm = mt.iloc[:,1:3]
mm.head()

### Pairplot

In [ ]:
sns.pairplot(mm)

In [ ]:
sns.pairplot(mm, hue = 'cyl')

In [ ]:
# Linear Regression

In [ ]:
import statsmodels.formula.api as smapi

In [ ]:
# Dependent mpg
# indep wt

In [ ]:
model1 = smapi.ols(formula = 'mpg ~ wt', data = mt).fit()
print(model1.summary())

In [ ]:
pred = model1.predict()
pred

In [ ]:
mt['prediction'] = pred
mt

In [ ]:
# Y = B0 + B1*X1
B0 = 37.2851
B1 = -5.3445
X1 = 2.620 # wt value from the table

Y = 37.2851 + (-5.3445)*(2.62)
Y

### Regression line or the best fitted line

In [ ]:
plt.plot(mt['wt'], mt['mpg'], 'o')
plt.plot(mt['wt'], pred, linewidth = 2)
plt.xlabel('wt')
plt.ylabel('mpg')
plt.title('mpg vs disp')

In [ ]:
# Multiple Linear Regression

In [ ]:
model2 = smapi.ols(formula = 'mpg ~ wt + disp + drat + vs + hp', data = mt).fit()
print(model2.summary())

In [ ]:
model3 = smapi.ols(formula = 'mpg ~ wt + cyl + drat + am + carb', data = mt).fit()
print(model3.summary())

In [ ]:
pred1 = model3.predict()
pred1

In [ ]:
mt['prediction1'] = pred1
mt

In [ ]:
# Y = B0 + B1*X1 + B2*X2 + B3*X3 + B4*X4 + B5*X5
#B0 = 32.9
#B1(WT) = -2.32
#(CYL) = -1.06
#B3(DRAT) = 0.85
#B4(AM) = 1.547
#B5(CARB) = 0.841
#B4


Y = 32.91 + (-2.32)*(2.62)+(-1.06)*(6) + (0.85)*(3.9)*(1.547)*(1)+(-0.841)*(4)
Y